### ISSUE TITLE
DeviantArt Outgoing link

### ISSUE THREAD

**Issue by ZatsuneSakurako** [mozlima/redirectbypasser#1]
Links like http://www.deviantart.com/users/outgoing?https://something... aren't detected, is there a way to do it?

**Comment by mozlima** [comment]
Maybe because missing tld or a malformed url.
http://www.deviantart.com/users/outgoing?https://something.com work!
Do you have other examples?

**Comment by ZatsuneSakurako** [comment]
It's not showing anything for me, a setting?

**Comment by mozlima** [comment]
http://www.deviantart.com/users/outgoing?https://something.com 
http://www.deviantart.com/users/outgoing?http://something.com
Dont work there? "https" and  "http" are added to the Advanced/protocol list? Maybe try a reset settings.

**Comment by ZatsuneSakurako** [comment]
Pressed reset but no change. Could out tell me if it's possible to make a pattern in the "Site" part?

**Comment by ZatsuneSakurako** [comment]
Oh wait, there's an error in the browser console "TypeError: document is null" background-common.js:337:7

**Comment by mozlima** [comment]
Hi, can you test version 2.1.1 if the problem still?

**Comment by ZatsuneSakurako** [comment]
Seems like this new version fix my problem, but that new version isn't signed yet. _sigh_ review take soooo much time. So, thanks fixing it.
I have tested the new system of "unlisted" (I dunno the exact English word) addon, much easier, except there's not the visibility on Mozilla website.

**Comment by mozlima** [comment]
thanks
